---
- name: Configure ElasticSearch repo
  copy:
    src: elasticsearch-yum-repo_{{ ansible_distribution_file_variety }}_{{ ansible_distribution_major_version }}
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0755
    owner: root
    group: root

- name: Install Elastic Package
  yum:
    name: elasticsearch
    state: present
